services:

  bot:
    build: .
    container_name: versions-bot
    restart: always
    volumes:
      - .:/code
      - ./data/data.yaml:/code/data/data.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_ID=$$\{bot.api_id\}
      - API_HASH=$$\{bot.api_hash\}
      - TOKEN=$$\{bot.token\}
      - DATABASE_URL=postgresql://$$\{bot.bd.user\}:$$\{bot.db.password\}@$$\{bot.db.host\}:$$\{bot.db.port\}/$$\{bot.db.db\}
    network_mode: host

volumes:
  postgres_data:
